### ISSUE TITLE
Android integration issue

### ISSUE THREAD

**Issue by abramenal** [bamlab/react-native-stripe#2]
I'm getting this exception
`java.lang.String cannot be cast to com.facebook.react.bridge.ReadableNativeMap`
when adding `new RNStripePackage()` to `getPackages()` method.

I have tried
Gradle v3.1.3 with sdk version 27 and build tools version 27.0.3 and
Gradle v3.0.0 with sdk version 26 and build tools version 26.0.2

Seems the library is not compatible with mentioned build tools.

Screenshot:
https://cdn.pbrd.co/images/Hzj8vvT.png

Seems the issue is reproducible only for android pipeline because on IOS the integration works properly.

Also seems you have a mistake in README.md since `getPackages` method is located in `MainApplication.java` class, not `MainActivity.java`.

**Comment by LPranulis** [comment]
Hi, did you find the solution?

**Comment by abramenal** [comment]
@LPranulis sorry it’s a year passed so don’t remember how I fixed that :(

**Comment by LPranulis** [comment]
I really need to fix this. Do not know where to start. On iOS everything works fine, but in Android it seems like it doesn't work, because in the Stripe dashboard cant see any new requests from Android.

**Comment by dgellisco** [comment]
I'm getting this too.

**Comment by LPranulis** [comment]
I didn't find the solution yet...
